<?php

return [
	'title' => 'Indonesia Book Vendor',
	'domain' => 'indonesiabookvendor.com',
	'phone' => '+62-21-565-2467',
	'address' => 'Jl. Kedoya Raya BB/8<br>Jakarta Barat 11520<br>Indonesia',
    'adminEmail' => 'contact@indonesiabookvendor.com',
	'senderEmail' => 'no-reply@mg.dnartworks.co.id',
    'defaultImage' => 'uploads/no-image.jpg',
	'newReleaseNumber' => 8,
	'bestSellerNumber' => 8,
	'featuredNumber' => -1, //give -1 if you want to show all featured books
	'tinyMceWidgetConf' => [
		'configs' => [
			'height' => 250,
			'plugins' => 'image, link',
			'toolbar' => [
				"undo redo | styleselect | bold italic underline strikethrough superscript subscript | link image | alignleft aligncenter alignright",
			],
			'menubar' => false,
		],
	],
	
	//mail content config
	'mail' => [
		'registration' => [
			'subject' => 'Indonesia Book Vendor Registration',
			'body' => '<p>Dear Mr/Ms/Mrs {last_name},</p><br>

						<p>We would like to inform you about the following message:<br>
						You have been registered. Now you can login to the website to manage your order .</p><br>

						<p>This e-mail is an autogenerated message. Should you have any queries,<br>
						please do not hesitate to send an e-mail to contact@indonesiabookvendor.com<br>
						instead of replying this message.</p><br><br>


						<p>Regards,<br>
						Indonesia Book Vendor</p>',
		],
		'order' => [
			'subject' => 'Your Order at Indonesia Book Vendor',
			'body' => '<p>Dear Mr/Ms/Mrs {last_name},</p><br>
				<p>We would like to inform you about the following message:<br>
				Thank you for ordering book with Indonesia Book Vendor.<br>
				This is the receipt of your order. Please save this reference until your
order has arrived.</p><br>
				
				<table border=0>
				<tr>
				<td width="50%">
				<b>{last_name}, {first_name}</b><br>
				{address}<br>
				{phone}<br>
				</td>
				<td width="50%">
				Order Number: #{order_id}<br>
				Order Date  : {order_date}<br><br>
				</td>
				</tr>
				</table>
				
				{orderlines}
				
				<b>Notes</b><br>
				{notes}<br><br><br>
				This e-mail is an autogenerated message. Should you have any queries,
				please do not hesitate to send an e-mail to contact@indonesiabookvendor.com
				instead of replying this message.<br><br><br>


				Regards,<br>
				Indonesia Book Vendor<br>
				',
		],
		'order-admin' => [
			'subject' => 'New Order at Indonesia Book Vendor',
			'body' => '<p>You have new book order. Please proccess this order.</p><br>
				
				<table border=0>
				<tr>
				<td width="50%">
				<b>{last_name}, {first_name}</b><br>
				{address}<br>
				{phone}<br>
				</td>
				<td width="50%">
				Order Number: #{order_id}<br>
				Order Date  : {order_date}<br><br>
				</td>
				</tr>
				</table>
				
				{orderlines}
				
				<b>Notes</b><br>
				{notes}<br><br>
				',
		],
	],
];
