name: 'indonesiabookvendor'
services:
  web:
    build:
      context: .
    ports:
      - "80:80"
    volumes:
      - ./../:/var/www/html
      - ./xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    links:
      - db
    env_file:
      - ./.env.development
    extra_hosts:
      - "host.docker.internal:host-gateway"
  db:
    image: mariadb:10.5.8
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mysql-db:/var/lib/mysql
    env_file:
      - ./.env.development
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.8
    ports:
      - "8000:80"
    links:
      - db
    env_file:
      - ./.env.development
