<?php

namespace App\Controllers;

class Migrate extends \CodeIgniter\Controller
{
	public function index()
	{
		// @phpstan-ignore-next-line
		$migrate = \Config\Services::migrations();
		// Set namespace to null to enable migration from all namespaces.

		$migrate->setNamespace(null);
		$version = $migrate->latest();

		$response = service('response');
		$response->setHeader("Content-type", "text/plain");

		if ($version === FALSE) {
			echo "Migration failed.";
		} else {
			echo "Migration success.";
			$this->writeStructure();
		}
	}

	private function writeStructure() {
		if ($_SERVER['REMOTE_ADDR'] === '::1' || $_SERVER['REMOTE_ADDR'] === '127.0.0.1') {
			$file = fopen('writable/DATABASE.md', 'w');
			fwrite($file, "# Database Structure\n\n");
			fwrite($file, "This document is autogenerated from `controllers/Migrate.php`\n\n");
			$db = db_connect();
			$tables = $db->listTables();
			foreach ($tables as $table) {
				$fields = $db->getFieldData($table);
				if (is_array($fields)) {
					fwrite($file, "* Table `$table`\n");
					foreach ($fields as $field) {
						fwrite($file, '    - `' . $field->name . '` ' . $field->type . '(' .
							$field->max_length . ')');
						if ($field->primary_key == 1) {
							fwrite($file, ' PRIMARY');
						}
						fwrite($file, "\n");
					}
				}
			}
			fclose($file);
		}
	}
}
